---
- name: arch-on-air hack playbook
  hosts: host
  connection: local
  vars:
    latest: false
    # Until ansible pacman module in 2.5 has been fixed...
    travis_ci: false
    gitsite: "git@github.com:"
    gitpath: "{{ lookup('env', 'HOME') }}/git/"
    gobootstrap: /usr/lib/go
  gather_facts: true
  tasks:
    - name: install developer tools
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - atom
        #- bc
        - gcc
        #- gcc-fortran
        - gdb
        - go
        - git
        - m4
        - make
        - autoconf
        - automake
        - libtool
        - pkg-config
        - unzip
        - cscope
        - stress
        - cpanminus
        - libmariadbclient
        - jre8-openjdk-headless
      become: true

    - name: install perf tools!
      pacman: name={{ item }} state=present update_cache=false
      items:
        - sysstat
      become: true

    - name: install kvm/docker tools for virtualization environment
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - qemu-headless
        - libvirt
        - libvirt-python2
        - virt-install
        - virt-viewer
        - tigervnc
        - docker
        - docker-machine
      become: true

    - name: add user to the developer groups
      user:
        name: "{{ lookup('env', 'USER') }}"
        append: true
        groups: libvirt,docker
      become: true
      when: not travis_ci|bool

    - name: create git root directory
      file: path={{ gitpath }} state=directory mode=0700

    - name: run the local docker registry
      docker_container:
        name: registry
        image: registry:2
        state: started
        restart: yes
        restart_policy: always
        ports:
          - "5000:5000"
      when: not travis_ci|bool

    - name: light the fire!
      import_tasks: tasks/all.yml
