---
- name: Setup password-less sudo {{ default_user }}
# =========================================
  hosts: all
  gather_facts: no

  remote_user: "root"
  become: true

  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Add sudoers users to wheel group
      user:
        name: "{{ item }}"
        groups: wheel
        shell: /bin/bash
        append: yes
        state: present
        createhome: yes
        generate_ssh_key: yes
        ssh_key_bits: 2048
      with_items:
        - "{{ default_user }}"

    - name: Set up authorized keys for the {{ default_user }} user
      authorized_key: user="{{ default_user }}" key="{{ item }}"
      with_file:
        - ~/.ssh/id_ed25519.pub
      when: inventory_hostname != "localhost"
      ignore_errors: true
...
