---
- name: arch-on-air post-installation playbook
  hosts: host
  connection: local
  vars:
    travis_ci: false
  gather_facts: false
  tasks:
    - name: install python2/3 as a start
      pacman: name={{ item }} state=present force=true update_cache=true
      items:
        - python
        - python-pip
        - python2
        - python2-pip
        - python2-six
      become: true

    - name: copy files under /etc
      copy:
        src: "files/etc/{{ item }}"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      items:
        - vconsole.conf
        - systemd/
        #- modprobe.d/
        - X11/xorg.conf.d/
      become: true

    - name: install console apps
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - vim
        - tmux
        - tree
        - jq
        - acpi
        - dialog
        - aspell
        - aspell-en
        - busybox
        - dosfstools
        - cowsay
        - pulseaudio
        - alsa-utils
      become: true

    - name: install network tools
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - w3m
        - elinks
        - curl
        - nmap
        - tcpdump
        - traceroute
        - net-tools
        - bind-tools
        - gnu-netcat
        - mtr
        - rsync
        - irssi
        - mutt
        - ebtables
        - dnsmasq
        - openconnect
        - wpa_supplicant
      become: true

    - name: install graphical libraries & tools
      pacman: name={{ item }} state=present force=true update_cache=true
      items:
        - gcr
        - libxft
        - libxinerama
        - xf86-video-intel
        - xf86-input-libinput
        - xf86-input-synaptics
        - xorg-server
        - xorg-xinit
        - xorg-xset
        - xorg-xsetroot
        - xorg-xinput
        - xorg-xprop
        - ttf-freefont
        - gtk3
        - webkit2gtk
        - mupdf
        - chromium
        - firefox
        - wireshark-gtk
      become: true

    #- name: configure the audio
    #  import_tasks: tasks/audio.yml
