---
- name: arch-on-air post-installation playbook
  hosts: host
  connection: local
  vars:
    travis_ci: false
  gather_facts: false
  tasks:
    #- name: first upgrade the system
    - name: Install Python using a raw SSH command to enable the execution of Ansible modules
      raw: pacman -S python --noconfirm
      args:
        executable: /bin/bash
      changed_when: false
      become: true

    - name: copy files under /etc
      copy:
        src: "files/etc/{{ item }}"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      items:
        - vconsole.conf
        - systemd/
        #- modprobe.d/
        - X11/xorg.conf.d/
      become: true

    - name: install HiDPI related fonts
      pacman: name={{ item }} state=present force=true update_cache=true
      items:
        - terminus-font
        - adobe-source-code-pro-fonts
      become: true
    
    - name: install wm stuff
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        #- lightdm
        #- lighdm-gtk-greeter
        - avahi
        - qt4 #for vlc
        - vlc
        - syncthing
        - xclip #utility to cli copy to clipboard
      become: true

      #- name: modify lightdm conf
      # 
        #greeter-session=lightdm-gtk-greeter
        #systemctl enable lightdm.service
        
    - name: install bonjour and macos network .local name recognition
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - avahi
        - nss-mdns
    - name: configure /etc/nssswitch.conf
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^hosts: '
        line: 'hosts: files mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns myhostname'
    - name: ensure avahi-daemon.service is enabled and started
      systemd:
        name: avahi-daemon.service
        state: started
        enabled: true
      become: true

    - name: install samba and configure
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - samba
      become: true
     #- name: install and configure Suckless st, dmenu, dwm
    #- name: modify st font and font size
    #- name: reconfigure systemd-journald.service to add /var hook problem solver 
    #   template: override.conf
    #   dest:  /etc/systemd/system/systemd-journald.service.d/override.conf
    #-name: modify virtual console font and font size
    # -name: download browser plugin and place them in the right config folder.
    # -name: configure ajust screen brightness buttons

    - name: install python2/3 as a start
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - python
        - python-pip
        - python2
        - python2-pip
        - python2-six
      become: true

    - name: install console apps
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - vim
        - emacs
        - tmux
        - tree
        - jq
        - acpi
        - dialog
        - aspell
        - aspell-en
        - busybox
        - dosfstools
        - cowsay
        - pulseaudio
        - alsa-utils
      become: true

    - name: install network tools
      pacman: name={{ item }} state=present force=true update_cache=false
      items:
        - w3m
        - elinks
        - curl
        - nmap
        - tcpdump
        - traceroute
        - net-tools
        - bind-tools
        - gnu-netcat
        - mtr
        - rsync
        - irssi
        - mutt
        - ebtables
        - dnsmasq
        - openconnect
        - wpa_supplicant
      become: true

    - name: install graphical libraries & tools
      pacman: name={{ item }} state=present force=true update_cache=true
      items:
        - gcr
        - libxft
        - libxinerama
        - xf86-video-intel
        - xf86-input-libinput
        - xf86-input-synaptics
        - xorg-server
        - xorg-xinit
        - xorg-xset
        - xorg-xsetroot
        - xorg-xinput
        - xorg-xprop
        - ttf-freefont
        - gtk3
        - webkit2gtk
        - mupdf
        - chromium
        - firefox
        - wireshark-gtk
      become: true

    #- name: configure the audio
    #  import_tasks: tasks/audio.yml
