---
- name: arch-on-air post-installation playbook
  hosts: host
  connection: local
  vars:
    travis_ci: false
  gather_facts: false
  tasks:
    - name: Install Python using a raw SSH command to enable the execution of Ansible modules
      raw: pacman -S python --noconfirm
      args:
        executable: /bin/bash
      changed_when: false
      become: true

    - name: first upgrade the system
      pacman:
        update_cache: yes
        upgrade: yes
      become: true
      register: packages
    - debug: var=packages
    
    - name: copy files under /etc
      copy:
        src: "files/etc/{{ item }}"
        dest: "/etc/{{ item }}"
        mode: 0644
        owner: root
        group: root
      items:
        - vconsole.conf
        - systemd/
        #- modprobe.d/
        - X11/xorg.conf.d/
      become: true

    - name: install HiDPI related fonts
      pacman: name={{ item }} state=latest
      items:
        - terminus-font
        - adobe-source-code-pro-fonts
      become: true
    
    - name: install wm stuff
      pacman: name={{ item }} state=latest
      items:
        #- lightdm
        #- lighdm-gtk-greeter
        - avahi
        - qt4 #for vlc
        - vlc
        - syncthing
        - xclip #utility to cli copy to clipboard
      become: true

      #- name: modify lightdm conf
      # 
        #greeter-session=lightdm-gtk-greeter
        #systemctl enable lightdm.service
        
    - name: install networkmanager, bonjour and macos network .local name recognition
      pacman: name={{ item }} state=latest
      items:
        - avahi
        - nss-mdns
        - networkmanager
        - ifplugd #to be able to detect and automount wired connections
        - wpa_actiond #to auto mount wireless connections
      become: true
    
    - name: configure /etc/nssswitch.conf
      lineinfile:
        path: /etc/nsswitch.conf
        regexp: '^hosts: '
        line: 'hosts: files mymachines mdns_minimal [NOTFOUND=return] resolve [!UNAVAIL=return] dns myhostname'
    - name: ensure avahi-daemon.service is enabled and started
      systemd:
        name: avahi-daemon.service
        state: started
        enabled: true
      become: true

    - name: ensure /etc/avahi/services is created to avoid boot msg error
      file:
        path: /etc/avahi/services
        state: directory
        mode: 0755
      become: true

    - name: ensure netctl-ifplugd@ens9.service is enabled and started
      systemd:
        name: netctl-ifplugd@ens9.service
        state: started
        enabled: true
      become: true
    
    - name: ensure netctl-auto@wlp3s0.service is enabled and started
      systemd:
        name: netctl-auto@wlp3s0.service
        state: started
        enabled: true
      become: true
    
    - name: install samba and configure
      pacman: name={{ item }} state=latest
      items:
        - samba
      become: true
     #- name: install and configure Suckless st, dmenu, dwm
    #- name: modify st font and font size
    #-name: modify virtual console font and font size
    # -name: download browser plugin and place them in the right config folder.
    # -name: configure ajust screen brightness buttons

    - name: install python2/3 as a start
      pacman: name={{ item }} state=latest
      items:
        - python
        - python-pip
        - python2
        - python2-pip
        - python2-six
      become: true

    - name: install console apps
      pacman: name={{ item }} state=latest
      items:
        - vim
        - emacs
        - tmux
        - tree
        - jq
        - acpi
        - dialog
        - aspell
        - aspell-en
        - busybox
        - dosfstools
        - cowsay
        - pulseaudio
        - alsa-utils
      become: true

    - name: install network tools
      pacman: name={{ item }} state=latest
      items:
        - w3m
        - elinks
        - curl
        - nmap
        - tcpdump
        - traceroute
        - net-tools
        - bind-tools
        - gnu-netcat
        - mtr
        - rsync
        - irssi
        - mutt
        - cyrus-sasl
        - ebtables
        - dnsmasq
        - openconnect
        - wpa_supplicant
      become: true
    
    #- name: configure mutt for gmail account
    #  template: 

    - name: install graphical libraries & tools
      pacman: name={{ item }} state=latest
      items:
        - gcr
        # lib needed to compile dwm
        - libxft
        - libxinerama
        - pkg-config
        # end
        - xf86-video-intel
        - xf86-input-libinput
        - xf86-input-synaptics
        - xorg-server
        - xorg-xinit
        - xorg-xset
        - xorg-xsetroot
        - xorg-xinput
        - xorg-xprop
        - ttf-freefont
        - gtk3
        - webkit2gtk
        - mupdf
        - chromium
        - firefox
        - wireshark-gtk
      become: true
    
    - name: checkout & make suckless dwm
      git:
        repo: 'http://git.suckless.org/dwm'
        dest: /home/jean/dwm

    - name: checkout & make suckless st
      git:
        repo: 'http://git.suckless.org/st'
        dest: /home/jean/st

    - name: checkout & make suckless dmenu
      git:
        repo: 'http://git.suckless.org/dmenu'
        dest: /home/jean/dmenu
    
    - name: copy st default config.def.h config.h     
      copy:
        src: /home/jean/st/config.def.h
        dest: /home/jean/st/config.h
    - name: configure st/config.h
      lineinfile:
        path: /home/jean/st/config.h
        regexp: '^char font'
        line: 'char font[] = "Source Code Pro:style=Semibold:size=8";'

    - name: make st
      make:
        chdir: /home/jean/st
    - name: make install st
      make:
        chdir: /home/jean/st
        target: install
      become: true

    - name: make dwm
      make:
        chdir: /home/jean/dwm
    - name: make install dwm
      make:
        chdir: /home/jean/dwm
        target: install
      become: true

    - name: make dmenu
      make:
        chdir: /home/jean/dmenu
    - name: make install dmenu
      make:
        chdir: /home/jean/dmenu
        target: install
      become: true

    #- name: configure the audio
    #  import_tasks: tasks/audio.yml
